### PR TITLE
Upgrade CumulusCI to 3.70.0 to remove load_dataset error

### PR DESCRIPTION
**Pull request by cryptolos**

### CODE REVIEW

**Comment by cryptolos** [comment]
@snehaheda please take a look at this one, just upgraded CumulusCI to get rid of the database connection error caused by `load_dataset`

Screen Shot 2022-12-06 at 20 05 44

**Comment by davidmreed** [comment]
Hi @cryptolos! I think you may have intended to open this PR against a fork of MetaDeploy. I'm delighted to see you're getting use from this product. Our current version is using CumulusCI 3.68.1 and will be updated to 3.70.0 soon. Thanks!

**Comment by davidmreed** [comment]
I'm going ahead and closing this PR out as it has some changes that I don't think were intended. Let us know if there's anything we can do to help.

**Comment by cryptolos** [comment]
@davidmreed sorry about that, I meant to create the PR based on our project. We just need to upgrade to CCI 3.70 because of some SF issues, but we managed to upgrade to the latest metadeploy version first and then will test the other upgrade. Thank you!

**Comment by davidmreed** [comment]
@cryptolos We'd _love_ to hear about how you're using MetaDeploy if you're willing to share!

**Pull request closed without merging**
