### PR TITLE
[improve-background-task-logging] Show error tracebacks from background jobs

### PR DESCRIPTION
**Pull request by wlonk**
cats

### CODE REVIEW

**Comment by davisagli** [comment]
As I said in slack, the current capturing of tracebacks for failed django-rq jobs is fine, so I don't think we need/want this change, at least for now. We do need tracebacks for exceptions in Django views to get logged though.

**Comment by wlonk** [comment]
@davisagli I seem to be getting full stacktraces in my console now; do you want to take a look and see if it does what you need?

**Comment by davisagli** [comment]
@wlonk I tried it -- now I see 2 copies of each traceback in the console

**Comment by wlonk** [comment]
@davisagli Hm, I'm getting that too. And it is completely unclear to me _why_. I will dig.

**Comment by davisagli** [comment]
@wlonk looks like I only get it once if I put `"propagate": False` on the `django.request` logger

**Comment by wlonk** [comment]
@davisagli can confirm, pushed that.

**Pull request merged**
