### PR TITLE
[realistic-plan] Add EDA to sample data

### PR DESCRIPTION
**Pull request by wlonk**
THIS RUNS FOR REAL. Be warned.

zeebree

### CODE REVIEW

**Comment by jgerigmeyer** [comment]
@wlonk Um, just to clarify... what does "THIS RUNS FOR REAL. Be warned." mean in practical terms? Should we not run this install in local dev? I thought the purpose of this was adding a real install that would still be harmless.

**Comment by wlonk** [comment]
It means it will modify your Salesforce instance. I am not sure how to make it "realistic" without doing that.

**Comment by jgerigmeyer** [comment]
@wlonk Right... but does that matter practically for our purposes?

**Comment by wlonk** [comment]
@jgerigmeyer to be honest, I don't know

**Comment by davisagli** [comment]
@jgerigmeyer @wlonk it should be fine as long as you're using a scratch org or a Developer Edition org or a sandbox rather than a production org. It should also be fine if you're using a production org and want to use EDA ;-)

**Pull request merged**
